# Uncomment the next line to define a global platform for your project
	 platform :ios, '9.0'

target 'HBD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  	use_frameworks!

  # Pods for HBD
	
	pod 'AFNetworking’, '~> 2.5.4’
 	pod 'SDWebImage', '~> 3.7.2'
 	pod 'Bugly', '~> 2.4.8’
    pod 'AvoidCrash', '~> 2.2.3’

 	pod 'IQKeyboardManager', '~> 5.0.2’
 	pod 'MJExtension', '~> 3.0.13’
 	pod 'MJRefresh', '~> 3.1.12’

 	pod 'Masonry', '~> 1.1.0’
 	pod 'YYText'
 	pod 'DZNEmptyDataSet'

 	pod 'UMCCommon'
 	pod 'UMCCommonLog'
 	pod 'UMCAnalytics'
 	pod 'UMCPush'
 	pod 'UMCShare/Social/WeChat'

  target 'HBDTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
